@host = http://localhost:3000

GET {{host}}/api/autores

###
GET {{host}}/api/autores/erdf

###
POST {{host}}/api/autores/
Content-Type: application/json

{
    "nombre": "Jesus2",
    "email": "jmartinez2@gmail.com",
    "img": "jmartinez2.jpg"
}
